---

# Manage installation tasks using pip

- name: 'INSTALL | PIP | Install packages globaly'
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ pew_pip_packages }}"
  when: "pew_install_globally | bool"
